name: "Build Goaccess"

on:
  push:
    branches:
    - main

jobs:
  build:
    name: "Build Goaccess"
    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
      - name: "Checkout latest codebase"
        uses: actions/checkout@v3

      # Refer : https://ghostty.org/docs/install/build
      - name: "Install Depenencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libmaxminddb-dev

      - name: "Build Goaccess binary"
        run: |
          wget https://tar.goaccess.io/goaccess-1.9.3.tar.gz
          tar -xzvf goaccess-1.9.3.tar.gz
          cd goaccess-1.9.3/
          ./configure --enable-utf8 --enable-geoip=mmdb
          make
          ls -la
